name: edict_py312
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  # Core Python
  - python=3.12
  - pip
  
  # PyTorch ecosystem (CPU version for macOS)
  - pytorch>=2.1.0
  - torchvision>=0.16.0
  - cpuonly  # CPU-only PyTorch for macOS
  
  # Core scientific computing
  - numpy>=1.24.0
  - scipy>=1.11.0
  - matplotlib>=3.7.0
  - pillow>=10.0.0
  - scikit-image>=0.21.0
  
  # Jupyter ecosystem
  - jupyter
  - notebook>=7.0.0
  - ipykernel
  - ipython>=8.15.0
  - jupyterlab
  
  # Image processing
  - opencv>=4.8.0
  - imageio>=2.31.0
  
  # System dependencies
  - ffmpeg
  - git
  
  # Pip dependencies
  - pip:
    # Hugging Face ecosystem (latest versions)
    - transformers>=4.35.0
    - diffusers>=0.24.0
    - huggingface-hub>=0.19.0
    - tokenizers>=0.15.0
    - accelerate>=0.24.0
    
    # Configuration and utilities
    - omegaconf>=2.3.0
    - tqdm>=4.66.0
    - einops>=0.7.0
    
    # Image processing and computer vision
    - albumentations>=1.3.0
    - kornia>=0.7.0
    - invisible-watermark>=0.2.0
    
    # Deep learning utilities
    - pytorch-lightning>=2.1.0
    - torchmetrics>=1.2.0
    - torch-fidelity>=0.3.0
    
    # Data handling
    - pandas>=2.1.0
    - pyarrow>=14.0.0
    
    # Visualization and monitoring
    - tensorboard>=2.15.0
    - matplotlib-inline>=0.1.6
    
    # File handling and utilities
    - pyyaml>=6.0.1
    - regex>=2023.10.0
    - ftfy>=6.1.0
    - filelock>=3.13.0
    - fsspec>=2023.10.0
    
    # Optional dependencies for enhanced functionality
    - safetensors>=0.4.0  # Safe tensor serialization
    
    # Development and debugging
    - ipdb  # Better debugger than pudb for modern Python
    
    # Compatibility shims if needed
    - typing-extensions>=4.8.0
